channels:
- pytorch
- fastai
- conda-forge
dependencies:
- catboost=1.0.3
- xgboost=1.5.1
- fastai=2.5.3
- flask=2.0.2
- h5py=3.1.0
- imageio=2.13.3
- keras=2.6.0
- loguru=0.5.3
- mkl=2021.4.0
- numpy=1.19.5
- pandas=1.3.5
- pillow=8.4.0
- pip=21.3.1
- pydantic=1.8.2
- pydap=3.2.2
- pyspark=3.2.1
- pytest=6.2.5
- python=3.9.7
- pytorch-cpu=1.10.0
- pytorch-lightning=1.5.5
- scikit-image=0.19.0
- scikit-learn=1.0.1
- scipy=1.7.3
- shapely=1.8.0
- tensorflow-cpu=2.6.2
- timm=0.4.12
- torchvision=0.11.1
- tqdm=4.62.3
- typer=0.4.1
- pip:
  - lightning-flash[image]==0.6.0
  - tailer==0.4.1
name: nasa-airport-config-runtime
